# Generated by Django 3.2.12 on 2023-01-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=100)),
                ('author', models.CharField(default='author', max_length=50)),
                ('pages_count', models.IntegerField(default=0)),
            ],
        ),
    ]
